In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
from scipy.stats import pearsonr

In [ ]:
dateparse = lambda dates: pd.datetime.strptime(dates, '%Y-%m')
dataPcorr = pd.read_csv('/content/drive/MyDrive/kolerasi/sutan.csv',  index_col='Tahun',  parse_dates = ['Tahun'], date_parser = dateparse)
print(dataPcorr.dtypes)

KasusDBD      int64
RR          float64
RH_avg      float64
ss          float64
dtype: object


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  """Entry point for launching an IPython kernel.


**KASUS DBD - Curah Hujan**

In [ ]:
newdataPcorr_temp = dataPcorr[['KasusDBD','RR']].dropna()
print(newdataPcorr_temp)

            KasusDBD     RR
Tahun                      
2015-01-01         9  16.72
2015-02-01        14  32.27
2015-03-01        14   9.27
2015-04-01        24   4.20
2015-05-01        18   2.78
...              ...    ...
2020-08-01         2   4.87
2020-09-01         1   0.55
2020-10-01         2   4.92
2020-11-01         2   4.98
2020-12-01         2   9.46

[72 rows x 2 columns]


In [ ]:
newdataPcorr_temp.corr()

KasusDBD        RR
KasusDBD  1.000000  0.065228
RR        0.065228  1.000000

In [ ]:
dbd_suhu = np.array(dataPcorr['KasusDBD'])
suhu = np.array(dataPcorr['RR'])

In [ ]:
np.corrcoef(dbd_suhu,suhu)

array([[1.       , 0.0652281],
       [0.0652281, 1.       ]])

In [ ]:
pearsonr(dataPcorr['KasusDBD'], dataPcorr['RR'])

(0.06522810488482322, 0.586185227101583)

**KASUS DBD - KELEMBAPAN**

In [ ]:
newdataPcorr_hum = dataPcorr[['KasusDBD','RH_avg']].dropna()
print(newdataPcorr_hum)

            KasusDBD  RH_avg
Tahun                       
2015-01-01         9   81.42
2015-02-01        14   83.61
2015-03-01        14   78.37
2015-04-01        24   77.10
2015-05-01        18   72.48
...              ...     ...
2020-08-01         2   73.87
2020-09-01         1   72.12
2020-10-01         2   76.00
2020-11-01         2   78.80
2020-12-01         2   80.00

[72 rows x 2 columns]


In [ ]:
newdataPcorr_hum.corr()

KasusDBD    RH_avg
KasusDBD  1.000000  0.311453
RH_avg    0.311453  1.000000

In [ ]:
dbd_hum = np.array(dataPcorr['KasusDBD'])
humadity = np.array(dataPcorr['RH_avg'])

In [ ]:
np.corrcoef(dbd_hum,humadity)

array([[1.        , 0.31145328],
       [0.31145328, 1.        ]])

In [ ]:
pearsonr(dataPcorr['KasusDBD'], dataPcorr['RH_avg'])

(0.3114532795723831, 0.007742301501726585)

**KASUS DBD - LAMANYA PENYINARAN MATAHARI**

In [ ]:
newdataPcorr_ss = dataPcorr[['KasusDBD','ss']].dropna()
print(newdataPcorr_ss)

            KasusDBD    ss
Tahun                     
2015-01-01         9  3.63
2015-02-01        14  4.13
2015-03-01        14  5.24
2015-04-01        24  5.58
2015-05-01        18  7.09
...              ...   ...
2020-08-01         2  7.75
2020-09-01         1  7.51
2020-10-01         2  6.75
2020-11-01         2  5.99
2020-12-01         2  3.81

[72 rows x 2 columns]


In [ ]:
newdataPcorr_ss.corr()

KasusDBD        ss
KasusDBD  1.000000 -0.143429
ss       -0.143429  1.000000

In [ ]:
dbd_ss = np.array(dataPcorr['KasusDBD'])
ss = np.array(dataPcorr['ss'])

In [ ]:
np.corrcoef(dbd_ss,ss)

array([[ 1.        , -0.14342871],
       [-0.14342871,  1.        ]])

In [ ]:
pearsonr(dataPcorr['KasusDBD'], dataPcorr['ss'])

(-0.1434287134944726, 0.22937929005446767)